### ISSUE TITLE
Dark mode button disappears on click (safari browser), this can be potentially harmful for sensitive eyes

### ISSUE THREAD

**Issue by LukaGrah** [NotNeelPatel/notneelpatel.github.io#2]

**Comment by NotNeelPatel** [comment]
I changed the theme of the website since this issue opened. Probably still an issue. Won't fix. Don't spam dark mode button please and thank you :)

**Comment by NotNeelPatel** [comment]
I changed the theme of the website since this issue opened. Probably still an issue. Won't fix. Don't spam dark mode button please and thank you :)
